# Generated by Django 6.0.3 on 2026-03-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubManagement', '0002_organization_created_at_organization_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='has_vp',
            new_name='has_two_vp',
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('PRES', 'President'), ('VP', 'Vice President'), ('VPI', 'Vice President Internal'), ('VPE', 'Vice President External'), ('SEC', 'Secretary'), ('TRE', 'Treasurer'), ('MEM', 'Member')], default='MEM', max_length=4),
        ),
    ]
